-- Engineer: Mnyar Hees
--
-- Create Date: 14 September
-- Design Name: vhdl2_uppgift_1a.vhd
-- Target Device: Intel/Altera MAX 10 (DE10-Lite board)
-- Tool Versions: Intel Quartus Prime & ModelSim - Intel FPGA Edition
-- Testbench File: (none included in this project)
-- Do File: -
--
-- Description:
-- This design generates a VGA 640x480 @ 60 Hz compatible video signal.
-- A 25 MHz pixel clock is created by dividing the 50 MHz system clock.
-- Horizontal (x_counter) and vertical (y_counter) counters are used to
-- generate the correct timing for VGA_HS (horizontal sync) and
-- VGA_VS (vertical sync) pulses.
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY vga_controller IS
    PORT 
    (
        CLOCK_50  : IN std_logic;                         -- 50 MHz system clock input
        RESET_N   : IN std_logic;                         -- Active-low reset input
        KEY       : IN std_logic_vector(2 DOWNTO 0);      -- Push-buttons for color selection
        VGA_HS    : OUT std_logic;                        -- Horizontal sync output
        VGA_VS    : OUT std_logic;                        -- Vertical sync output
        VGA_R     : OUT std_logic_vector(3 DOWNTO 0);     -- 4-bit red color channel
        VGA_G     : OUT std_logic_vector(3 DOWNTO 0);     -- 4-bit green color channel
        VGA_B     : OUT std_logic_vector(3 DOWNTO 0)      -- 4-bit blue color channel
    );
END vga_controller;

ARCHITECTURE rtl OF vga_controller IS

    --------------------------------------------------------------------
    -- Internal signals
    --------------------------------------------------------------------
    SIGNAL clk_25 : std_logic := '0';                     -- 25 MHz pixel clock (generated by dividing CLOCK_50)
    SIGNAL x_counter : unsigned(9 DOWNTO 0) := (OTHERS => '0'); -- Horizontal pixel counter (0–799)
    SIGNAL y_counter : unsigned(9 DOWNTO 0) := (OTHERS => '0'); -- Vertical pixel counter   (0–524)

    -- Two-stage synchronizer for reset to avoid metastability
    SIGNAL reset_n_t1 : std_logic := '0';
    SIGNAL reset_n_t2 : std_logic := '0';

BEGIN

    --------------------------------------------------------------------
    -- Reset synchronizer: ensures RESET_N is safely synchronized
    -- to the system clock to prevent metastability issues.
    --------------------------------------------------------------------
    Metastability_Handler : PROCESS (CLOCK_50, RESET_N)
    BEGIN
        IF RESET_N = '0' THEN
            reset_n_t1 <= '0';
            reset_n_t2 <= '0';
        ELSIF rising_edge(CLOCK_50) THEN
            reset_n_t1 <= '1';
            reset_n_t2 <= reset_n_t1;
        END IF;
    END PROCESS;

    --------------------------------------------------------------------
    -- Clock divider: divides 50 MHz clock by 2 to generate 25 MHz
    -- required for VGA 640x480 @ 60 Hz pixel rate.
    --------------------------------------------------------------------
    Clock_Divider : PROCESS (CLOCK_50, reset_n_t2)
    BEGIN
        IF reset_n_t2 = '0' THEN
            clk_25 <= '0';
        ELSIF rising_edge(CLOCK_50) THEN
            clk_25 <= NOT clk_25;
        END IF;
    END PROCESS;

    --------------------------------------------------------------------
    -- Horizontal and vertical counters:
    -- Count pixels and lines according to VGA timing parameters.
    -- Horizontal: 0–799 (visible area + front porch + sync + back porch)
    -- Vertical:   0–524
    --------------------------------------------------------------------
    PROCESS (clk_25, reset_n_t2)
    BEGIN
        IF reset_n_t2 = '0' THEN
            x_counter <= (OTHERS => '0');
            y_counter <= (OTHERS => '0');
        ELSIF rising_edge(clk_25) THEN
            
            -- End of scanline
            IF x_counter = 799 THEN
                x_counter <= (OTHERS => '0');

                -- End of frame
                IF y_counter = 524 THEN
                    y_counter <= (OTHERS => '0');
                ELSE
                    y_counter <= y_counter + 1;
                END IF;

            ELSE
                x_counter <= x_counter + 1;
            END IF;

        END IF;
    END PROCESS;

    --------------------------------------------------------------------
    -- VGA sync signal generation
    -- These signals go LOW during the sync pulse regions.
    --------------------------------------------------------------------
    VGA_HS <= '0' WHEN x_counter >= 656 AND x_counter < 752 ELSE '1'; -- Horizontal sync pulse width
    VGA_VS <= '0' WHEN y_counter >= 490 AND y_counter < 492 ELSE '1'; -- Vertical sync pulse width

    --------------------------------------------------------------------
    -- RGB color output based on KEY inputs:
    -- When a button is pressed (active low), a colored rectangle appears.
    --------------------------------------------------------------------
    VGA_R <= "1111" WHEN (x_counter < 360 AND y_counter < 320 AND KEY(0) = '1')
             ELSE (OTHERS => '0'); -- Red area

    VGA_G <= "1111" WHEN (x_counter < 410 AND y_counter >= 280 AND KEY(1) = '1')
             ELSE (OTHERS => '0'); -- Green area

    VGA_B <= "1111" WHEN (x_counter >= 300 AND y_counter >= 240 AND KEY(2) = '1')
             ELSE (OTHERS => '0'); -- Blue area

END rtl;

